DEFAULT = 0

LANGUAGES_CHOICES = [
    ('chinese', 'Китайский'),
    ('arabic', 'Арабский'),
    ('hindi', 'Хинди'),
    ('english', 'Английский'),
    ('spanish', 'Испанский'),
    ('bengali', 'Бенгальский'),
    ('portuguese', 'Португальский'),
    ('russian', 'Русский'),
    ('japanese', 'Японский'),
    ('german', 'Немецкий'),
    ('korean', 'Корейский'),
    ('french', 'Французский'),
    ('javanese', 'Яванский'),
    ('telugu', 'Телугу'),
    ('marathi', 'Маратхи'),
    ('vietnamese', 'Вьетнамский'),
    ('tamil', 'Тамильский'),
    ('italian', 'Итальянский'),
    ('turkish', 'Турецкий'),
    ('urdu', 'Урду'),
    ('punjabi', 'Панджаби'),
    ('ukrainian', 'Украинский'),
    ('gujarati', 'Гуджарати'),
    ('thai', 'Тайский'),
    ('polish', 'Польский'),
    ('malayalam', 'Малаялам'),
    ('kannada', 'Каннада'),
    ('odia', 'Ория'),
    ('burmese', 'Бирманский'),
    ('azerbaijani', 'Азербайджанский'),
    ('persian', 'Персидский'),
    ('sundanese', 'Сунданский'),
    ('pashto', 'Пушту'),
    ('romanian', 'Румынский'),
    ('bhojpuri', 'Бходжпури'),
    ('hausa', 'Хауса'),
    ('maithili', 'Майтхили'),
    ('malaysian', 'Малайский'),
    ('serbo_croatian', 'Сербохорватский'),
    ('awadhi', 'Авадхи'),
    ('uzbek', 'Узбекский'),
    ('yoruba', 'Йоруба'),
    ('dutch', 'Нидерландский'),
    ('sindhi', 'Синдхи'),
    ('igbo', 'Игбо'),
    ('amharic', 'Амхарский'),
    ('oromo', 'Оромо'),
    ('indonesian', 'Индонезийский'),
    ('tagalog', 'Тагальский'),
    ('nepali', 'Непальский'),
    ('assamese', 'Ассамский'),
    ('saraiki', 'Сараики'),
    ('cebuano', 'Себуанский'),
    ('hungarian', 'Венгерский'),
    ('chittagonian', 'Читтагонг'),
    ('zhuang', 'Чжуанский'),
    ('shona', 'Шона'),
    ('madurese', 'Мадурский'),
    ('sinhalese', 'Сингальский'),
    ('marwari', 'Марвари'),
    ('magahi', 'Магахи'),
    ('haryanvi', 'Харьянви'),
    ('greek', 'Греческий'),
    ('czech', 'Чешский'),
    ('chhattisgarhi', 'Чхаттисгархи'),
    ('fula', 'Фула'),
    ('dakhni', 'Дакхни'),
    ('malagasy', 'Малагасийский'),
    ('belarusian', 'Белорусский'),
]

PRIVACY_CHOICES = [
    ('open', 'Открытый профиль'),
    ('friends_only', 'Только для друзей'),
    ('private', 'Закрытый профиль')
]
