# Generated by Django 5.1.5 on 2025-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('COM', 'Completed'), ('PP', 'Postponed'), ('DR', 'Dropped'), ('CAN', 'Cancelled')], default=('IP', 'In Progress'), max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
